project:
  render:
    - published-202301-chagneux-macrolitter.qmd

title: "Macrolitter video counting on riverbanks using state space models and moving cameras "
subtitle: ""
author:
  - name: "Mathis Chagneux"
    corresponding: true
    email: mathis.chagneux@telecom-paris.fr
    url: https://www.linkedin.com/in/mathis-chagneux-140245158/?originalSubdomain=fr
    affiliation: Telecom Paris, LTCI
    affiliation-url: https://www.telecom-paris.fr/fr/recherche/laboratoires/laboratoire-traitement-et-communication-de-linformation-ltci
  - name: "Sylvain Le Corff"
    email: sylvain.le_corff@sorbonne-universite.fr
    url: https://sylvainlc.github.io/
    orcid: 0000-0001-5211-2328
    affiliation: Sorbonne Université, UMR 8001 (LPSM)
    affiliation-url: https://www.lpsm.paris/
  - name: "Pierre Gloaguen"
    email: pierre.gloaguen@agroparistech.fr
    url: https://papayoun.github.io/
    orcid: 0000-0003-2239-5413
    affiliation: AgroParisTech, UMR MIA 518
    affiliation-url: https://mia-ps.inrae.fr/
  - name: "Charles Ollion"
    email: charles.ollion@gmail.com
    url: https://charlesollion.github.io/
    orcid: 0000-0002-6763-701X
    affiliation: Naia Science
  - name: "Océane Lepâtre"
    email: olepatre@surfrider.eu
    url: https://fr.linkedin.com/in/oc%C3%A9ane-lep%C3%A2tre-675b38116
    orcid: None
    affiliation: Surfrider Foundation Europe
    affiliation-url: https://surfrider.eu/
  - name: "Antoine Bruge"
    email: antoine.bruge@outlook.com
    url: https://www.linkedin.com/in/antoinebruge/
    orcid: 0000-0002-0548-234X
    affiliation: Surfrider Foundation Europe
    affiliation-url: https://surfrider.eu/ 
date: 2023-02-16
date-modified: last-modified
abstract: >+
    Litter is a known cause of degradation in marine environments and most of
    it travels in rivers before reaching the oceans. In this paper, we present
    a novel algorithm to assist waste monitoring along watercourses. While
    several attempts have been made to quantify litter using neural object
    detection in photographs of floating items, we tackle the more challenging
    task of counting directly in videos using boat-embedded cameras. We rely
    on multi-object tracking (MOT) but focus on the key pitfalls of false and
    redundant counts which arise in typical scenarios of poor detection
    performance. Our system only requires supervision at the image level and
    performs Bayesian filtering via a state space model based on optical flow.
    We present a new open image dataset gathered through a crowdsourced
    campaign and used to train a center-based anchor-free object detector.
    Realistic video footage assembled by water monitoring experts is annotated
    and provided for evaluation. Improvements in count quality are
    demonstrated against systems built from state-of-the-art multi-object
    trackers sharing the same detection capabilities. A precise error
    decomposition allows clear analysis and highlights the remaining
    challenges.
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.57750/845m-f805"
  publisher: "French Statistical Society"
  issn: "2824-7795"
google-scholar: true
bibliography: references.bib
github-user: computorg
repo: "published-202301-chagneux-macrolitter"
draft: false
published: true
format:
  computo-html: default
  computo-pdf: default
jupyter: python3

