name: computo
channels:
    - conda-forge
dependencies:
    - jupyter
    - numpy
    - matplotlib
    - scipy 
    - pip
    - pandas 
    - tqdm
    - seaborn
    - pycocotools
    - filterpy
    - scikit-image
    - pykalman
    - pip:
        - opencv_python
        - pytk
